remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Blog de Informes DigiVision"
description: "Informes y publicaciones"
exclude:
  - README.md
  - /proyecto1/Informe.md
  - /proyecto1/README.md
